- name: Template secret file
  template:
    src:  templates/additional.postgresql.secret.yaml.j2
    dest: /tmp/additional.postgresql.secret.yaml
    force: true

- name: Secret applied
  shell: kubectl apply -f /tmp/additional.postgresql.secret.yaml -n {{ tenant_name }}-service 