- name: Secret shared across namespace
  shell: |
    kubectl get secret redis -n {{ tenant_name }}-datastore -o yaml | sed 's/namespace: .*/namespace: {{ tenant_name}}-service/' | kubectl apply -f -
  ignore_errors: true